'use strict';
const test = require('node:test'), assert = require('node:assert/strict');
const fs = require('node:fs'), os = require('node:os'), path = require('node:path');
const { Store } = require('../src/core/store.cjs');
const catalog = require('../src/data/catalog.cjs');
const recipes = require('../src/data/game-index.json').entries.filter((e) => e.kind === '配方');
function setup(t) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'yijian-craft-plans-'));
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }));
  return { dir, store: new Store(dir, catalog) };
}
test('saved plans and their goals retain recipe quantities after the editor changes or the app reloads', (t) => {
  const { dir, store } = setup(t);
  const original = [{ id: recipes[0].id, quantity: 2 }, { id: recipes[1].id, quantity: 3 }];
  store.mutate({ type: 'craft-plan-save', name: '武当出行', list: original, addGoal: true });
  original[0].quantity = 99;
  let p = store.get().profiles[0];
  const id = p.craftPlans[0].id;
  assert.equal(p.goals[0].source.id, id);
  store.mutate({ type: 'craft-set', id: recipes[2].id, quantity: 1 });
  p = new Store(dir, catalog).get().profiles[0];
  assert.equal(p.craftPlans[0].list.length, 2);
  assert.equal(p.craftPlans[0].list[0].quantity, 2);
  store.mutate({ type: 'craft-plan-open', id });
  p = store.get().profiles[0];
  assert.deepEqual(p.craftList, p.craftPlans[0].list);
  assert.deepEqual(p.previousCraftList, [{ id: recipes[2].id, quantity: 1 }]);
  store.mutate({ type: 'craft-draft-restore' });
  assert.equal(store.get().profiles[0].craftList[0].id, recipes[2].id);
});
test('opening and undoing plans restores allocation and editor ownership, including identical recipe lists', (t) => {
  const { dir, store } = setup(t), list = [{ id: recipes[0].id, quantity: 1 }];
  store.mutate({ type: 'craft-set', ...list[0] });
  store.mutate({ type: 'craft-draft-reserve', value: false });
  store.mutate({ type: 'craft-plan-save', name: '不保留的原计划', list, reserved: false });
  const originalId = store.get().profiles[0].activeCraftPlanId;
  store.mutate({ type: 'craft-plan-save', name: '保留的另一个计划', list, reserved: true });
  const otherId = store.get().profiles[0].activeCraftPlanId;
  store.mutate({ type: 'craft-plan-open', id: originalId });
  store.mutate({ type: 'craft-plan-open', id: otherId });
  assert.equal(store.get().profiles[0].reserveCraftDraft, true);
  store.mutate({ type: 'craft-draft-restore' });
  const p = new Store(dir, catalog).get().profiles[0];
  assert.equal(p.activeCraftPlanId, originalId);
  assert.equal(p.reserveCraftDraft, false);
  assert.equal(p.previousCraftContext.activeCraftPlanId, otherId);
  assert.equal(p.previousCraftContext.reserveCraftDraft, true);
});
test('plan update is explicit, duplicate creates a separate plan, and live goal references cannot be orphaned', (t) => {
  const { store } = setup(t), list = [{ id: recipes[0].id, quantity: 1 }];
  store.mutate({ type: 'craft-plan-save', name: '计划一', list, addGoal: true });
  const id = store.get().profiles[0].craftPlans[0].id;
  store.mutate({ type: 'craft-plan-save', name: '计划二', list });
  store.mutate({ type: 'craft-plan-save', id, name: '计划一更新', list: [{ ...list[0], quantity: 4 }], addGoal: true });
  const p = store.get().profiles[0];
  assert.equal(p.goals.length, 1);
  assert.equal(p.craftPlans.find((x) => x.id === id).list[0].quantity, 4);
  assert.equal(p.craftPlans.find((x) => x.id !== id).list[0].quantity, 1);
  assert.throws(() => store.mutate({ type: 'craft-plan-remove', id }), /行囊目标/);
  store.mutate({ type: 'goal-remove', id: p.goals[0].id });
  store.mutate({ type: 'craft-plan-remove', id });
  assert.equal(store.get().profiles[0].craftPlans.length, 1);
});
test('plans remain isolated across profiles and invalid imports preserve current state', (t) => {
  const { store } = setup(t);
  store.mutate({ type: 'craft-plan-save', name: '第一周目', list: [{ id: recipes[0].id, quantity: 1 }], addGoal: true });
  const original = store.get(), first = original.activeProfileId, id = original.profiles[0].craftPlans[0].id;
  store.mutate({ type: 'profile-add', name: '第二周目' });
  assert.throws(() => store.mutate({ type: 'craft-plan-open', id }), /当前周目/);
  store.mutate({ type: 'profile-switch', id: first });
  const before = store.get(), invalid = store.get();
  invalid.profiles[0].craftPlans[0].list[0].quantity = -1;
  assert.throws(() => store.importData(invalid));
  assert.deepEqual(store.get(), before);
  const missing = store.get(); missing.profiles[0].craftPlans = [];
  assert.throws(() => store.importData(missing), /备料引用/);
  store.importData(store.get());
  assert.equal(store.get().profiles[0].goals[0].source.id, id);
});
test('plan copies and editor undo retain their own processing choices', (t) => {
  const { store } = setup(t), list = [{ id: 'fusion-1000', quantity: 1 }];
  store.mutate({ type: 'craft-set', ...list[0] });
  store.mutate({ type: 'craft-choice', itemId: '10216', recipeId: 'fusion-9500' });
  store.mutate({ type: 'craft-plan-save', name: '原计划', list });
  const original = store.get().profiles[0].craftPlans[0];
  store.mutate({ type: 'craft-choice', itemId: '10216', recipeId: '' });
  store.mutate({ type: 'craft-plan-save', name: '副本', list: original.list, choices: original.choices });
  assert.deepEqual(store.get().profiles[0].craftPlans[0].choices, original.choices);
  assert.notEqual(store.get().profiles[0].activeCraftPlanId, store.get().profiles[0].craftPlans[0].id);
  store.mutate({ type: 'craft-plan-open', id: original.id });
  assert.deepEqual(store.get().profiles[0].craftChoices, { '10216': 'fusion-9500' });
  store.mutate({ type: 'craft-draft-restore' });
  assert.deepEqual(store.get().profiles[0].craftChoices, {});
});
